apiVersion: apps/v1
kind: Deployment
metadata:
  name: anderspetersson-se
spec:
  selector:
    matchLabels:
      app: anderspetersson-se
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: anderspetersson-se
    spec:
      imagePullSecrets:
        - name: gcp-artifact-registry
      containers:
        - name: nginx
          image: europe-west1-docker.pkg.dev/roiiogcloud/anderspetersson-se/anderspetersson-se:latest
          imagePullPolicy: Always
          ports:
            - name: nginx
              containerPort: 8300
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
