apiVersion: v1
kind: Service
metadata:
  labels:
    app: anderspetersson-se
  name: anderspetersson-se
spec:
  type: ClusterIP
  selector:
    app: anderspetersson-se
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
